#!/usr/bin/env bash
cd $DOTFILES/custom-scripts/help_files/
if [ ! -f custom_scripts.txt ] ; then
	echo "No help available"
	exit 1;
fi
if [ $# -eq 0 ]; then
	man -l custom_scripts.txt
	exit 0;
fi

if [ $1 = "raw" ]; then
	cat custom_scripts.txt
	exit 0;
fi

exit 1;
