return {
    "luisiacc/gruvbox-baby",
    "k-lar/gruvbox-pale",
    "f4z3r/gruvbox-material.nvim",
    "Almo7aya/neogruvbox.nvim",
    "catppuccin/vim",
    "catppuccin/nvim",
    "nordtheme/vim",
    "shaunsingh/nord.nvim",
    "AlexvZyl/nordic.nvim",
    "pappasam/papercolor-theme-slim",
    "chitalu/vim-papercolor-theme",
    "mohvn/peachpuff-legacy",
    "lifepillar/vim-gruvbox8",
    "ellisonleao/gruvbox.nvim",
    "ricardoraposo/gruvbox-minor.nvim",
}